const books = [
  {
    id: 1,
    isbn: '978-3-16-148410-0',
    doi: '10.1000/xyz123',
    titulo: 'El Arte de Enseñar: Más Allá del Aula',
    ano_publicacion: 2010,
    editorial: 'Editorial Alfa',
    pais: 'México',
    idioma: 'Español',
    isbn_traduccion: '978-0-12-345678-9',
    idioma_traduccion: 'Inglés',
    titulo_traduccion: 'Example Book 1',
    apoyo_conahcyt: true,
    rol_autor: 'Autor Principal',
    estado_publicacion: 'Publicado',
    objetivo: 'Investigar el tema X',
    dictaminado: true,
    portada: 'https://example.com/portada1.jpg'
  },
  {
    id: 2,
    isbn: '978-3-16-148411-7',
    doi: '10.1000/xyz124',
    titulo: 'Pedagogía Creativa: Innovación en la Enseñanza',
    ano_publicacion: 2015,
    editorial: 'Editorial Beta',
    pais: 'Argentina',
    idioma: 'Español',
    isbn_traduccion: '978-0-12-345679-6',
    idioma_traduccion: 'Francés',
    titulo_traduccion: 'Exemple Livre 2',
    apoyo_conahcyt: false,
    rol_autor: 'Coautor',
    estado_publicacion: 'Publicado',
    objetivo: 'Explorar el tema Y',
    dictaminado: false,
    portada: 'https://example.com/portada2.jpg'
  },
  {
    id: 3,
    isbn: '978-3-16-148412-4',
    doi: '10.1000/xyz125',
    titulo: 'Semillas del Conocimiento: Cultivando Mentes Jóvenes',
    ano_publicacion: 2020,
    editorial: 'Editorial Gamma',
    pais: 'España',
    idioma: 'Español',
    isbn_traduccion: '978-0-12-345680-2',
    idioma_traduccion: 'Alemán',
    titulo_traduccion: 'Beispiel Buch 3',
    apoyo_conahcyt: true,
    rol_autor: 'Editor',
    estado_publicacion: 'En revisión',
    objetivo: 'Analizar el tema Z',
    dictaminado: true,
    portada: 'https://example.com/portada3.jpg'
  },
  {
    id: 4,
    isbn: '978-3-16-148413-1',
    doi: '10.1000/xyz126',
    titulo: 'La Ciencia de la Educación: Estrategias y Teorías Modernas',
    ano_publicacion: 2012,
    editorial: 'Editorial Delta',
    pais: 'Chile',
    idioma: 'Español',
    isbn_traduccion: '978-0-12-345681-9',
    idioma_traduccion: 'Portugués',
    titulo_traduccion: 'Livro Exemplo 4',
    apoyo_conahcyt: false,
    rol_autor: 'Revisor',
    estado_publicacion: 'Publicado',
    objetivo: 'Estudiar el tema W',
    dictaminado: false,
    portada: 'https://example.com/portada4.jpg'
  },
  {
    id: 5,
    isbn: '978-3-16-148414-8',
    doi: '10.1000/xyz127',
    titulo: 'Historias de Aula: Narrativas de un Docente',
    ano_publicacion: 2018,
    editorial: 'Editorial Épsilon',
    pais: 'Perú',
    idioma: 'Español',
    isbn_traduccion: '978-0-12-345682-6',
    idioma_traduccion: 'Italiano',
    titulo_traduccion: 'Libro Esempio 5',
    apoyo_conahcyt: true,
    rol_autor: 'Coeditor',
    estado_publicacion: 'En revisión',
    objetivo: 'Investigar el tema V',
    dictaminado: true,
    portada: 'https://example.com/portada5.jpg'
  },
  {
    id: 6,
    isbn: '978-3-16-148415-5',
    doi: '10.1000/xyz128',
    titulo: 'El Desafío de Enseñar: Retos y Triunfos Educativos',
    ano_publicacion: 2017,
    editorial: 'Editorial Zeta',
    pais: 'Colombia',
    idioma: 'Español',
    isbn_traduccion: '978-0-12-345683-3',
    idioma_traduccion: 'Chino',
    titulo_traduccion: '例子书6',
    apoyo_conahcyt: false,
    rol_autor: 'Autor Principal',
    estado_publicacion: 'Publicado',
    objetivo: 'Explorar el tema U',
    dictaminado: false,
    portada: 'https://example.com/portada6.jpg'
  },
  {
    id: 7,
    isbn: '978-3-16-148416-2',
    doi: '10.1000/xyz129',
    titulo: 'La Magia de la Educación Inclusiva',
    ano_publicacion: 2016,
    editorial: 'Editorial Eta',
    pais: 'Uruguay',
    idioma: 'Español',
    isbn_traduccion: '978-0-12-345684-0',
    idioma_traduccion: 'Japonés',
    titulo_traduccion: '例の本7',
    apoyo_conahcyt: true,
    rol_autor: 'Coautor',
    estado_publicacion: 'En revisión',
    objetivo: 'Analizar el tema T',
    dictaminado: true,
    portada: 'https://example.com/portada7.jpg'
  },
  {
    id: 8,
    isbn: '978-3-16-148417-9',
    doi: '10.1000/xyz130',
    titulo: 'Formando el Futuro: Guía para Educadores del Siglo XXI',
    ano_publicacion: 2021,
    editorial: 'Editorial Theta',
    pais: 'Venezuela',
    idioma: 'Español',
    isbn_traduccion: '978-0-12-345685-7',
    idioma_traduccion: 'Ruso',
    titulo_traduccion: 'Пример Книга 8',
    apoyo_conahcyt: false,
    rol_autor: 'Revisor',
    estado_publicacion: 'Publicado',
    objetivo: 'Estudiar el tema S',
    dictaminado: false,
    portada: 'https://example.com/portada8.jpg'
  }
]

export default {
  getAll: () => books
}
