export const Country = [
  { iso_code: 'ZA', country: 'Sudáfrica' },
  { iso_code: 'AT', country: 'Austria' },
  { iso_code: 'IN', country: 'India' },
  { iso_code: 'AF', country: 'Afganistán' },
  { iso_code: 'AL', country: 'Albania' },
  { iso_code: 'DE', country: 'Alemania' },
  { iso_code: 'AD', country: 'Andorra' },
  { iso_code: 'AO', country: 'Angola' },
  { iso_code: 'AI', country: 'Anguila' },
  { iso_code: 'AQ', country: 'Antártida' },
  { iso_code: 'AG', country: 'Antigua y Barbuda' },
  { iso_code: 'AN', country: 'Antillas Neerlandesas' },
  { iso_code: 'SA', country: 'Arabia Saudita' },
  { iso_code: 'DZ', country: 'Argelia' },
  { iso_code: 'AR', country: 'Argentina' },
  { iso_code: 'AM', country: 'Armenia' },
  { iso_code: 'AW', country: 'Aruba' },
  { iso_code: 'AU', country: 'Australia' },
  { iso_code: 'AZ', country: 'Azerbaiyán' },
  { iso_code: 'BE', country: 'Bélgica' },
  { iso_code: 'BA', country: 'Bosnia y Herzegovina' },
  { iso_code: 'BS', country: 'Bahamas' },
  { iso_code: 'BD', country: 'Bangladés' },
  { iso_code: 'BH', country: 'Baréin' },
  { iso_code: 'BB', country: 'Barbados' },
  { iso_code: 'BZ', country: 'Belice' },
  { iso_code: 'BJ', country: 'Benín' },
  { iso_code: 'BM', country: 'Bermudas' },
  { iso_code: 'BY', country: 'Bielorrusia' },
  { iso_code: 'MM', country: 'Birmania' },
  { iso_code: 'BO', country: 'Bolivia' },
  { iso_code: 'BW', country: 'Botsuana' },
  { iso_code: 'BR', country: 'Brasil' },
  { iso_code: 'BN', country: 'Brunéi' },
  { iso_code: 'BG', country: 'Bulgaria' },
  { iso_code: 'BI', country: 'Burundi' },
  { iso_code: 'BF', country: 'Burkina Faso' },
  { iso_code: 'BT', country: 'Bután' },
  { iso_code: 'CV', country: 'Cabo Verde' },
  { iso_code: 'CM', country: 'Camerún' },
  { iso_code: 'KH', country: 'Camboya' },
  { iso_code: 'CA', country: 'Canadá' },
  { iso_code: 'QA', country: 'Catar' },
  { iso_code: 'KZ', country: 'Kazajistán' },
  { iso_code: 'TD', country: 'Chad' },
  { iso_code: 'CL', country: 'Chile' },
  { iso_code: 'CN', country: 'China' },
  { iso_code: 'CY', country: 'Chipre' },
  { iso_code: 'CO', country: 'Colombia' },
  { iso_code: 'KM', country: 'Comoras' },
  { iso_code: 'CG', country: 'Congo-Brazzaville' },
  { iso_code: 'CD', country: 'Congo-Kinshasa' },
  { iso_code: 'KP', country: 'Corea del Norte' },
  { iso_code: 'KR', country: 'Corea del Sur' },
  { iso_code: 'CR', country: 'Costa Rica' },
  { iso_code: 'CI', country: 'Costa de Marfil' },
  { iso_code: 'HR', country: 'Croacia' },
  { iso_code: 'CU', country: 'Cuba' },
  { iso_code: 'DK', country: 'Dinamarca' },
  { iso_code: 'DM', country: 'Dominica' },
  { iso_code: 'EG', country: 'Egipto' },
  { iso_code: 'AE', country: 'Emiratos Árabes Unidos' },
  { iso_code: 'EC', country: 'Ecuador' },
  { iso_code: 'ER', country: 'Eritrea' },
  { iso_code: 'SK', country: 'Eslovaquia' },
  { iso_code: 'SI', country: 'Eslovenia' },
  { iso_code: 'ES', country: 'España' },
  { iso_code: 'EE', country: 'Estonia' },
  { iso_code: 'US', country: 'Estados Unidos' },
  { iso_code: 'ET', country: 'Etiopía' },
  { iso_code: 'FO', country: 'Islas Feroe' },
  { iso_code: 'FJ', country: 'Fiyi' },
  { iso_code: 'PH', country: 'Filipinas' },
  { iso_code: 'FI', country: 'Finlandia' },
  { iso_code: 'FR', country: 'Francia' },
  { iso_code: 'GM', country: 'Gambia' },
  { iso_code: 'GA', country: 'Gabón' },
  { iso_code: 'GH', country: 'Ghana' },
  { iso_code: 'GE', country: 'Georgia' },
  { iso_code: 'GS', country: 'Georgia del Sur y las Islas Sandwich del Sur' },
  { iso_code: 'GI', country: 'Gibraltar' },
  { iso_code: 'GR', country: 'Grecia' },
  { iso_code: 'GD', country: 'Granada' },
  { iso_code: 'GL', country: 'Groenlandia' },
  { iso_code: 'GP', country: 'Guadalupe' },
  { iso_code: 'GU', country: 'Guam' },
  { iso_code: 'GT', country: 'Guatemala' },
  { iso_code: 'GY', country: 'Guyana' },
  { iso_code: 'GF', country: 'Guayana Francesa' },
  { iso_code: 'GN', country: 'Guinea' },
  { iso_code: 'GQ', country: 'Guinea Ecuatorial' },
  { iso_code: 'GW', country: 'Guinea-Bisáu' },
  { iso_code: 'HT', country: 'Haití' },
  { iso_code: 'HN', country: 'Honduras' },
  { iso_code: 'HK', country: 'Hong Kong' },
  { iso_code: 'HU', country: 'Hungría' },
  { iso_code: 'YE', country: 'Yemen' },
  { iso_code: 'BV', country: 'Isla Bouvet' },
  { iso_code: 'NF', country: 'Isla Norfolk' },
  { iso_code: 'CX', country: 'Isla Christmas' },
  { iso_code: 'KY', country: 'Islas Caimán' },
  { iso_code: 'CK', country: 'Islas Cook' },
  { iso_code: 'FK', country: 'Islas Malvinas' },
  { iso_code: 'HM', country: 'Islas Heard y McDonald' },
  { iso_code: 'MH', country: 'Islas Marshall' },
  { iso_code: 'UM', country: 'Islas menores alejadas de los Estados Unidos' },
  { iso_code: 'SB', country: 'Islas Salomón' },
  { iso_code: 'TC', country: 'Islas Turcas y Caicos' },
  { iso_code: 'VI', country: 'Islas Vírgenes de EE. UU.' },
  { iso_code: 'VG', country: 'Islas Vírgenes Británicas' },
  { iso_code: 'CC', country: 'Islas Cocos' },
  { iso_code: 'ID', country: 'Indonesia' },
  { iso_code: 'IR', country: 'Irán' },
  { iso_code: 'IQ', country: 'Irak' },
  { iso_code: 'IE', country: 'Irlanda' },
  { iso_code: 'IS', country: 'Islandia' },
  { iso_code: 'IL', country: 'Israel' },
  { iso_code: 'IT', country: 'Italia' },
  { iso_code: 'JM', country: 'Jamaica' },
  { iso_code: 'JP', country: 'Japón' },
  { iso_code: 'DJ', country: 'Yibuti' },
  { iso_code: 'JO', country: 'Jordania' },
  { iso_code: 'YU', country: 'Yugoslavia' },
  { iso_code: 'KW', country: 'Kuwait' },
  { iso_code: 'LB', country: 'Líbano' },
  { iso_code: 'LY', country: 'Libia' },
  { iso_code: 'LA', country: 'Laos' },
  { iso_code: 'LS', country: 'Lesoto' },
  { iso_code: 'LV', country: 'Letonia' },
  { iso_code: 'LR', country: 'Liberia' },
  { iso_code: 'LI', country: 'Liechtenstein' },
  { iso_code: 'LT', country: 'Lituania' },
  { iso_code: 'LU', country: 'Luxemburgo' },
  { iso_code: 'MX', country: 'México' },
  { iso_code: 'MC', country: 'Mónaco' },
  { iso_code: 'MO', country: 'Macao' },
  { iso_code: 'MK', country: 'Macedonia' },
  { iso_code: 'MG', country: 'Madagascar' },
  { iso_code: 'MY', country: 'Malasia' },
  { iso_code: 'MW', country: 'Malawi' },
  { iso_code: 'MV', country: 'Maldivas' },
  { iso_code: 'ML', country: 'Malí' },
  { iso_code: 'MT', country: 'Malta' },
  { iso_code: 'MP', country: 'Islas Marianas del Norte' },
  { iso_code: 'MA', country: 'Marruecos' },
  { iso_code: 'MQ', country: 'Martinica' },
  { iso_code: 'MU', country: 'Mauricio' },
  { iso_code: 'MR', country: 'Mauritania' },
  { iso_code: 'YT', country: 'Mayotte' },
  { iso_code: 'FM', country: 'Micronesia' },
  { iso_code: 'MZ', country: 'Mozambique' },
  { iso_code: 'MD', country: 'Moldavia' },
  { iso_code: 'MN', country: 'Mongolia' },
  { iso_code: 'MS', country: 'Montserrat' },
  { iso_code: 'NE', country: 'Níger' },
  { iso_code: 'NA', country: 'Namibia' },
  { iso_code: 'NR', country: 'Nauru' },
  { iso_code: 'NP', country: 'Nepal' },
  { iso_code: 'NI', country: 'Nicaragua' },
  { iso_code: 'NG', country: 'Nigeria' },
  { iso_code: 'NU', country: 'Niue' },
  { iso_code: 'NO', country: 'Noruega' },
  { iso_code: 'NC', country: 'Nueva Caledonia' },
  { iso_code: 'NZ', country: 'Nueva Zelanda' },
  { iso_code: 'OM', country: 'Omán' },
  { iso_code: 'NL', country: 'Países Bajos' },
  { iso_code: 'PW', country: 'Palaos' },
  { iso_code: 'PA', country: 'Panamá' },
  { iso_code: 'PG', country: 'Papúa Nueva Guinea' },
  { iso_code: 'PK', country: 'Pakistán' },
  { iso_code: 'PY', country: 'Paraguay' },
  { iso_code: 'PE', country: 'Perú' },
  { iso_code: 'PN', country: 'Pitcairn' },
  { iso_code: 'PL', country: 'Polonia' },
  { iso_code: 'PF', country: 'Polinesia Francesa' },
  { iso_code: 'PR', country: 'Puerto Rico' },
  { iso_code: 'PT', country: 'Portugal' },
  { iso_code: 'KE', country: 'Kenia' },
  { iso_code: 'KG', country: 'Kirguistán' },
  { iso_code: 'KI', country: 'Kiribati' },
  { iso_code: 'RU', country: 'Rusia' },
  { iso_code: 'GB', country: 'Reino Unido' },
  { iso_code: 'CF', country: 'República Centroafricana' },
  { iso_code: 'CZ', country: 'República Checa' },
  { iso_code: 'DO', country: 'República Dominicana' },
  { iso_code: 'RE', country: 'Reunión' },
  { iso_code: 'RO', country: 'Rumania' },
  { iso_code: 'RW', country: 'Ruanda' },
  { iso_code: 'KN', country: 'San Cristóbal y Nieves' },
  { iso_code: 'SM', country: 'San Marino' },
  { iso_code: 'PM', country: 'San Pedro y Miquelón' },
  { iso_code: 'ST', country: 'Santo Tomé y Príncipe' },
  { iso_code: 'VC', country: 'San Vicente y las Granadinas' },
  { iso_code: 'SY', country: 'Siria' },
  { iso_code: 'SV', country: 'El Salvador' },
  { iso_code: 'WS', country: 'Samoa' },
  { iso_code: 'AS', country: 'Samoa Americana' },
  { iso_code: 'SH', country: 'Santa Elena' },
  { iso_code: 'LC', country: 'Santa Lucía' },
  { iso_code: 'EH', country: 'Sahara Occidental' },
  { iso_code: 'SC', country: 'Seychelles' },
  { iso_code: 'SN', country: 'Senegal' },
  { iso_code: 'SL', country: 'Sierra Leona' },
  { iso_code: 'SG', country: 'Singapur' },
  { iso_code: 'SO', country: 'Somalia' },
  { iso_code: 'LK', country: 'Sri Lanka' },
  { iso_code: 'SE', country: 'Suecia' },
  { iso_code: 'CH', country: 'Suiza' },
  { iso_code: 'SZ', country: 'Suazilandia' },
  { iso_code: 'SD', country: 'Sudán' },
  { iso_code: 'SR', country: 'Surinam' },
  { iso_code: 'SJ', country: 'Svalbard y Jan Mayen' },
  { iso_code: 'TH', country: 'Tailandia' },
  { iso_code: 'TW', country: 'Taiwán' },
  { iso_code: 'TJ', country: 'Tayikistán' },
  { iso_code: 'TZ', country: 'Tanzania' },
  { iso_code: 'IO', country: 'Territorio Británico del Océano Índico' },
  { iso_code: 'TF', country: 'Territorios Australes Franceses' },
  { iso_code: 'TL', country: 'Timor-Leste' },
  { iso_code: 'TG', country: 'Togo' },
  { iso_code: 'TK', country: 'Tokelau' },
  { iso_code: 'TO', country: 'Tonga' },
  { iso_code: 'TT', country: 'Trinidad y Tobago' },
  { iso_code: 'TN', country: 'Túnez' },
  { iso_code: 'TM', country: 'Turkmenistán' },
  { iso_code: 'TR', country: 'Turquía' },
  { iso_code: 'TV', country: 'Tuvalu' },
  { iso_code: 'UA', country: 'Ucrania' },
  { iso_code: 'UG', country: 'Uganda' },
  { iso_code: 'UY', country: 'Uruguay' },
  { iso_code: 'UZ', country: 'Uzbekistán' },
  { iso_code: 'VU', country: 'Vanuatu' },
  { iso_code: 'VA', country: 'Vaticano' },
  { iso_code: 'VE', country: 'Venezuela' },
  { iso_code: 'VN', country: 'Vietnam' },
  { iso_code: 'WF', country: 'Wallis y Futuna' },
  { iso_code: 'ZM', country: 'Zambia' },
  { iso_code: 'ZW', country: 'Zimbabue' }
]
